### ISSUE TITLE
Enable code coverage for nBallerina repo

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/nballerina-cpp#131]
**Description:**
We also need to think about $subject. We have started working on this for other repos in the Ballerina organization. We need to capture the coverage and see how we are progressing over time.

We are using jacoco to generate coverage data and codecov to publish coverage data and visualize it. For example please check - https://app.codecov.io/gh/ballerina-platform/module-ballerina-graphql

I was checking whether we can do the same for c++ projects and codecov has support for that too - https://github.com/codecov/example-c

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruvi-d** [comment]
Let's hold this till #116 since it will make it easier to add a new target.

Also, these are the compiler and linker options we need to enable via CMake to get coverage stats: https://github.com/lefticus/cpp_starter_project/blob/master/cmake/Sanitizers.cmake#L6

**Comment by ruvi-d** [comment]
Got it working: https://github.com/ruvi-d/nballerina/tree/ruvi/task/code-coverage

![image](https://user-images.githubusercontent.com/6542630/110455557-9973b180-80ee-11eb-897c-c0ec9abaf8cb.png)
