### ISSUE TITLE
Global variables are not intialized

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina-cpp#135]
**Description:**
Global variable initialization is happening in the `..<init>` functions, which codegen is currently skipping. Thus all global variables are left uninitialized.

**Suggested Labels:**
Type/Feature, Priority/High

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
#134

**Comment by Kishanthan** [comment]
Blocked by https://github.com/ballerina-platform/nballerina/issues/149
