### ISSUE TITLE
Add test case for Abort

### ISSUE THREAD

**Issue by ramakotareddy** [ballerina-platform/nballerina-cpp#181]
Add test case to handle Abort functionality.

_Originally posted by @ramakotareddy in https://github.com/ballerina-platform/nballerina/issues/168#issuecomment-799514902_

**Comment by ruvi-d** [comment]
Blocked on #188

**Comment by ruvi-d** [comment]
We need to replicate the same erors as jballerina side https://docs.google.com/document/d/1qjQTIMjpedZTGTNVXRg3WggmmjcAS23SkY4yxn_teDQ/edit

**Comment by ramakotareddy** [comment]
Create test case of Array out of bound Access Abort functionality #223
