### ISSUE TITLE
Windows PR build workflow

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/nballerina-cpp#208]
**Description:**
We need to add a workflow for windows PR build by fixing the caching issues faced currently. 

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
Should address this comment here https://github.com/ballerina-platform/nballerina/pull/189#discussion_r597410480
