### ISSUE TITLE
Casting anydata or optional string to string create invalid results in ballerina swan lake alpha 4

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina-cpp#255]
**Description:**
If we call the print_string function with a constant string value and then call it again with an anydata or optional string cast to string in the function call it will still print the previous constant string

**Steps to reproduce:**
Fallowing code will fail giving output "RESULT=RESULT="
```
public function print_string(string val) = external;

public function main() {
    string? str = "Hello World!";
    print_string("RESULT=");
    print_string(<string>str);
}
```
However fallowing code will work giving the correct output "Hello World!Result="
```
public function print_string(string val) = external;

public function main() {
    string? str = "Hello World!";
    print_string(<string>str);
    print_string("RESULT=");    
}
```
Fallowing will also work correctly giving the result "RESULT=Hello World!"
```
public function print_string(string val) = external;

public function main() {
    string? str = "Hello World!";
    string x = <string>str;
    print_string("RESULT=");
    print_string(x);
}
```
Same situation happens if `str` is of type `anydata` as well
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shubhamnarlawar** [comment]
Please try to keep issue description as small as possible. You can give details in the description.

for example - issue title can be - `Casting anydata or optional string to string in ballerina swan lake alpha 4`

**Comment by ruvi-d** [comment]
The problem boils down to when we call a function passing a temp string created from a casted smrt.ptr.
I had a quick look with the LLVM IR and it seems that the only difference is that with alpha-4, that we are reusing a local variable to hold the temp string value. Not sure why it fails, but we might have to check the disassembled code to figure out why this local variable is holding the previous assigned value.

**Comment by ruvi-d** [comment]
Also note that we tried compiling the LLVM IR with `-O0 -g`, bug this bug was reproducible.

**Comment by heshanpadmasiri** [comment]
I think this an #257 are caused by the same reason because they both have the same differences in the LLVM IR files.
