### ISSUE TITLE
Implement array access

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina-cpp#274]
**Description:**
Implement array access of int array

Depends on #272

Array access has to depend on `inherentType` if it's not current type it has to cast. This could ether be upcast or a downcast.
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ruvi-d** [comment]
@manuranga : would you mind adding the examples to cover the scope of this requirement?

**Comment by heshanpadmasiri** [comment]
@manuranga : for clarification is this is to handle cases such as
```
    int[] arr = [5];
    float x = 5.0 + arr[0];
```
Because if so compiler front end adds a type cast after array access (which due to a bug doesn't work properly in nballerina)

**Comment by manuranga** [comment]
Here by casting, i mean up-cast down-cast we need to handle in array access it self. Cases where there are no casts injected by the frontend.

 eg:
```
int[] i = [1,2];
any[] aa = i;


any x = a[1];
```
I'll post few more examples later
