### ISSUE TITLE
comparison always printing false

### ISSUE THREAD

**Issue by ramakotareddy** [ballerina-platform/nballerina-cpp#276]
With below test case, always printing false.

    float a = 5.5;
    float b = 5.5;
    print_boolean(a >= b);  // print true

_Originally posted by @ruvi-d in https://github.com/ballerina-platform/nballerina/pull/271#discussion_r618923745_

**Comment by KavinduZoysa** [comment]
Please note that a couple of test cases are disabled in PR https://github.com/ballerina-platform/nballerina/pull/281, due to this issue. Those tests should be enabled under this PR.

**Comment by ramakotareddy** [comment]
@ruvi-d, Now printing true with below test, without any changes in source code

float a = 5.5;
float b = 5.5;
print_boolean(a >= b);   // printing true

and getting expected output from disabled float tests(i have enabled locally and all tests are passing).

Can i enable those disabled float tests if every thing pass successfully ?

**Comment by ruvi-d** [comment]
Yes. I suppose that they should be enabled. 
Did you switch compilers from GCC to Clang?

**Comment by ramakotareddy** [comment]
@ruvi-d, in testRunScript.sh we are using clang only. do we need to change in any other places ? Please suggest.

**Comment by ruvi-d** [comment]
> @ruvi-d, in testRunScript.sh we are using clang only. do we need to change in any other places ? Please suggest.

no no.. just asked to figure out what the change was. Master branch build recently switched from using gcc to clang-11 for nballerina, so was just wondering whether the test started to pass after we switched compilers.

**Comment by ramakotareddy** [comment]
@ruvi-d, i think that is the issue. In the old builds we got unexpected results with float comparison and i have tested today with new build and it's working.  And jballerina is also updated. We don't have old builds to figure out the exact issue.

**Comment by shubhamnarlawar** [comment]
Can we close this issue then?
