### ISSUE TITLE
Document the BIR Specification

### ISSUE THREAD

**Issue by ayonam** [ballerina-platform/nballerina-cpp#34]
**Description:**
Currently we only have a documentation of the BIR representation in the serialized format as emitted by the jBallerina compiler.  We do not have a formal documentation of the BIR Specification itself.  Document the BIR specification and ensure that the new documentation is in sync with the existing documentation of the serialized BIR.

**Suggested Labels:**

**Suggested Assignees:**
@sameerajayasoma @manuranga @Kishanthan @uthaiyashankar 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shubhamnarlawar** [comment]
Is this task done
