### ISSUE TITLE
Pipeline BIR binary output from the FE to the BE

### ISSUE THREAD

**Issue by ayonam** [ballerina-platform/nballerina-cpp#36]
**Description:**
Currently, the BIR binary output is serialized and written out to a file by the Front End and the Back End reads that output from the file and deserializes it.  @Kishanthan proposed to remove this mechanism in favour of a seamless flow of BIR data without the intermediate file.  This issue is to discuss the possible approaches to this problem and a final implementation of the same.

**Suggested Labels:**

**Suggested Assignees:**
@shubhamnarlawar @Kishanthan @manuranga @sameerajayasoma @uthaiyashankar @ayonam 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shubhamnarlawar** [comment]
This would eliminate BIR Reader completely. 

In which phase this issue needs to be addressed?
