### ISSUE TITLE
Array initialization values not being set

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina-cpp#85]
**Description:**
In the following .bal code
```
int _bal_result = 0;
public function main() {
    int[] arr1 = [1,2,3];
    _bal_result = arr1[2];
}
```
Does not return `3` as expected.
this is the main from the generated .ll
```
define i32 @main() {
entry:
  %"%0" = alloca i32, align 4
  %"%1" = alloca i32, align 4
  %"%3" = alloca i32, align 4
  %"%4" = alloca i32, align 4
  %"%5" = alloca i32, align 4
  %"%6" = alloca i32, align 4
  %"%8" = alloca i32, align 4
  br label %bb0

bb0:                                              ; preds = %entry
  store i32 -1, i32* %"%3", align 4
  store i32 1, i32* %"%4", align 4
  store i32 2, i32* %"%5", align 4
  store i32 3, i32* %"%6", align 4
  %"%3_temp" = load i32, i32* %"%3", align 4
  %0 = call i32 @new_int_array(i32 %"%3_temp")
  store i32 %0, i32* %"%1", align 4
  store i32 2, i32* %"%8", align 4
  %"%8_temp" = load i32, i32* %"%8", align 4
  %1 = call i32* @int_array_load(i32* %"%1", i32 %"%8_temp")
  %2 = load i32, i32* %1, align 4
  store i32 %2, i32* @_bal_result, align 4
  br label %bb2

bb1:                                              ; No predecessors!
  br label %bb2

bb2:                                              ; preds = %bb1, %bb0
  %retrun_temp = load i32, i32* @_bal_result, align 4
  ret i32 %retrun_temp
}
```
The values `[1.2.3]` does not appear to be set to the array

**Suggested Labels:**
type/bug priority/high

**Suggested Assignees:**
@shubhamnarlawar

**Comment by ayonam** [comment]
Although the array is being allocated by calling a rust function, the initialization of the same is being done on a local allocation.  The locations %4, %5 and %6 are being allocated on the local stack for this purpose.  This is wrong.  In case Rust has the concept of variable argument functions, you can have a rust function like new_int_array_with_init(), which can take up additional parameters as initial values.  You can then build a function call to such a variable argument function with the initial values as the additional parameters, that will also initialize the array after creating it.

Alternately, you can generate code like what is being done to read the element at index 2.  Something like the following:

%1 = call i32* @int_array_load(i32* %"%1", i32 0)
store i32 1, i32* %1, align 4
%2 = call i32* @int_array_load(i32* %"%1", i32 1)
store i32 2, i32* %2, align 4
%3 = call i32* @int_array_load(i32* %"%1", i32 2)
store i32 3, i32* %3, align 4

Notice how I change the index in the call and the data in the store instructions.

**Comment by ruvi-d** [comment]
@Kishanthan I am looking at the BIR to figure out how the initialization values should be loaded. 
I am using the following test app.
```
int _bal_result = 0;
public function main() {
    int[] arr1 = [1,2,3];
    _bal_result = arr1[2];
}
```
The problem is that I don't see instructions for initialization in the BIR dump. Which is
```
public main function() -> () {
    %0(RETURN) ();
    %0(RETURN) ();
    %1(LOCAL) int[];
    %3(TEMP) int;
    %4(TEMP) int;
    %5(TEMP) int;
    %6(TEMP) int;
    %8(TEMP) int;

    bb0 {
        %3 = ConstLoad -1;
        %4 = ConstLoad 1;
        %5 = ConstLoad 2;
        %6 = ConstLoad 3;
        %1 = newArray int[][%3];
        %8 = ConstLoad 2;
        _bal_result = %1[%8];
        %0 = ConstLoad 0;
        GOTO bb2;
```
As you can see the initializing values are being loaded to TEMP int variables (%4, %5 and %6), but at no point are they associated with the Array (%1).
I checked the binary BIR dump with Kaitai and couldn't spot any additional info. Only the LHS and Size are associated with the INSTRUCTION_KIND_NEW_ARRAY instruction.

How do you guys do array initialization in jBallerina?

**Comment by warunalakshitha** [comment]
We are using initial values from java bir model new array instruction. It seems we do not dump those initial values in the new array instruction to bir dump. 

https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java#L368

https://github.com/ballerina-platform/ballerina-lang/blob/331925fb8916e154cca8331489235a94db6eb7fb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java#L274

Seems like a bug for me. @Kishanthan @manuranga

**Comment by manuranga** [comment]
Ya looks like a bug in https://github.com/ballerina-platform/ballerina-lang/blob/800161670167211da8ed7e84a83b65f46e2426e2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java#L325

need fix it and get a new pack.

**Comment by ruvi-d** [comment]
Noted. I think we will have to fix this for other data types like Maps too. The initialization values appears to be missing in that too.

**Comment by Kishanthan** [comment]
Yes, its a bug. This is not found because we directly use the BIRModel at the jBallerina backend.
